# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('lecturer', models.CharField(max_length=200)),
                ('myCourses_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.IntegerField(verbose_name='Overall stars')),
                ('lectures', models.IntegerField(verbose_name='Lecture stars')),
                ('assignments', models.IntegerField(verbose_name='Assignment stars')),
                ('workload', models.IntegerField(verbose_name='Workload stars')),
                ('comments', models.TextField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
