# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='course_code',
            new_name='course_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comments',
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.DateField(),
        ),
    ]
