# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20161109_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
